### ISSUE TITLE
Regression in rule handling

### ISSUE THREAD

**Issue by Aluriak** [textX/textX#166]
I was messing around examples in order to test CLI extensibility for doc generation, and got some weird behavior when switching from distributed version to master.

Here is an example:

    import textx

    grammar = """
    DSL:
        commands*=BaseCommand;
    BaseCommand:
        (Require | Group) '.'?;

    Require:
        'require' /[a-z]/;
    Group:
        'group' hello=/[0-9]/;
    """

    metamodel = textx.metamodel_from_str(grammar)

With current distributed version (the one installed by pip, 1.8.0), i got no problem. Now, if i use the master branch (by cloning this repository), i got the following stacktrace:

    Traceback (most recent call last):
      File "test.py", line 16, in <module>
        metamodel = textx.metamodel_from_str(grammar)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/metamodel.py", line 597, in metamodel_from_str
        language_from_str(lang_desc, metamodel)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/lang.py", line 931, in language_from_str
        TextXVisitor(parser, metamodel))
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/arpeggio/__init__.py", line 1244, in visit_parse_tree
        getattr(visitor, "second_%s" % sa_name)(asg_node)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/lang.py", line 218, in second_textx_model
        self._determine_rule_types(model_parser.metamodel)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/lang.py", line 369, in _determine_rule_types
        _determine_rule_type(cls)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/lang.py", line 365, in _determine_rule_type
        _add_reffered_classes(rule, cls._tx_inh_by, start=True)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/lang.py", line 353, in _add_reffered_classes
        _add_reffered_classes(r, inh_by)
      File "/home/lbourneu/Documents/projects/textx-dsldoc/venv/lib/python3.6/site-packages/textX-1.8.0-py3.6.egg/textx/lang.py", line 358, in _add_reffered_classes
        'is not allowed.'.format(cls.__name__))
    textx.exceptions.TextXSemanticError: b'Referencing multiple rules from a single choice of abstract rule "BaseCommand" is not allowed.'

Removing the `hello=` do fixes the problem.

The other way to fix it is to create an intermediate rule, like this:

    BaseCommand:
        BaseCommandRaw '.'?;
    BaseCommandRaw:
        Require | Group;

Is seems to me that it is a regression. Or is it linked to #155 ?

**Comment by igordejanovic** [comment]
Thanks for the report and sorry, I totally missed this issue. Stumbled upon it today as I was working on some object processor calling issues.

This do look like a regression related to #134 and #128 and indeed this PR introduced check that disallows referencing multiple rules from a single alternative of abstract rule. In this case it seems that it got it wrong.

I'm investigating the issue.

BTW, if nobody responds on the issue for a week or so please ping the tread by asking on progress. We should at least put labels whether it is a bug or some expected behavior.
