### ISSUE TITLE
This is possible with textX?

### ISSUE THREAD

**Issue by paulocoutinhox** [textX/textX#203]
Hi,

I want create a djinni DSL parser because the project was stopped:
https://github.com/dropbox/djinni/blob/master/test-suite/djinni/yaml-test.djinni

This is possible with TEXT X?

More samples to understand:
https://github.com/dropbox/djinni/tree/master/test-suite/djinni

There is any help here to start parsing interfaces, records, constants, enums with TEXT X?

Thanks.

**Comment by goto40** [comment]
In principle, the task of parsing seems possible (without having checked details).

However, parsing is only a very small aspect. Think of all the validation of the model (documented __and__ undocumented aspects!) and all the target language specific tweaks...

I am a very big fan of our textx (great tool, easy to use, few dependencies)! But you should also check if it is maybe cheaper to maintain the original code base...

**Comment by paulocoutinhox** [comment]
Ok. I understand. I know everything about what i need do and how to write a parser like djinni in the same model of original, only reading line by line. But i want use some python parser to be more concise.

But im confused about how it works. Because i only see simple examples of parsing only a small set of things.

To parse djinni i will need parse some different syntax and objects:

RECORDS:

```
customer = record +c {
    id: i64;
    name: string;
    addrress: optional<string>;
    set_list : list<set<string>>;
} deriving (eq, ord, parcelable)
```

INTERFACES:

```
my_interface = interface +j +o +c {
    get_one(record_id: i64): customer;
    find_all(): list<customer>;
    static insert(new_customer: customer): i64;
    static delete_all();
}
```

CONSTANTS:

```
constants = record {
    const bool_constant: bool = true;
    const int_constant: i32 = 1;
}
```

INTERFACES WITH CONSTANTS:

```
constants_interface = interface +c {
    const bool_constant: bool = true;
    const i8_constant: i8 = 1;
}
```

FLAGS

```
access_flags = flags {
  nobody = none;
  owner_read;
  owner_write;
  owner_execute;
  group_read;
  group_write;
  group_execute;
  system_read;
  system_write;
  system_execute;
  everybody = all;
}
```

ENUM

```
color = enum {
	red;
	orange;
	yellow;
	green;
	blue;
	indigo;
	violet;
}
```

COMMENTS

```
Lines starting with # or //
```

Can you help me start? This tool that i want develop will be part of ezored (https://ezored.com). My open source tool for C++ SDK.

Thanks.

**Comment by igordejanovic** [comment]
Since this language, if I understand, describe structural aspects the best example to start from is [Entity](https://github.com/textX/textX/tree/master/examples/Entity). 

You have already identified language concepts so it is easy to start by making textX rules out of them.

Like, for example:

```
Record: 'record' flags*=Flag '{'
   fields+=RecordField  // each record contains "fields" attribute which is a list of "RecordField" instances
'}';
Flag: '+c' | '+j' | '+o'; // etc
RecordField: name=ID ':' type=Type;  //RecordField has "name" and "type"
Type: SimpleType | ComplexType;  // Type can be simple or complex
SimpleType: 'int' | 'string'; // etc.
CompexType: OptionalType | ContainerType;
OptionalType: 'optional<' inner_type=SimpleType '>';
ContainerType: kind=ContainerKind  '<' inner_type=Type '>';
ContainerKind: 'list' | 'set';
```
Try to run through some of [the tutorials](http://textx.github.io/textX/stable/tutorials/entity/) first. I guess that will make things more clear.
Start with a basic rules like just describe records and then describe a file containing multiple records like this:
```
File: variable+=Variable;
Variable: name=ID '=' value=Record;
```
Start with a simple example file with just the simple stuff you want to parse first (e.g. just a record with several fields), write a grammar for it and extend it gradually adding more stuff.
You will get a hang of it pretty fast I'm sure.

Also, the tests are invaluable source of information. See for example https://github.com/textX/textX/tree/master/tests/functional/test_scoping/components_model1

If you hit into some specific problem, let us know, we'll be glad to help.

**Comment by paulocoutinhox** [comment]
Hi,

Im making the tool and have some problems with textX, but  true that is my mistake. I have some questions.

1 - In my record model i need support "deriving" tag. But im getting error:

```
RecordModel:
   records+=Record
;

Record:
   name=ID '=' 'record' flags*=Flag '{'
   fields+=RecordField
'}'
'deriving' '(' derivings*=Deriving ')'
;

Flag: '+' name=ID; // Flag has "name"
Deriving: ',' name=ID; // Deriving has "name"
RecordField: name=ID ':' type=Type ';';  // RecordField has "name" and "type"
Type: SimpleType | ComplexType;  // Type can be simple or complex
SimpleType: name=ID; // Can be any string that will be check by code
ComplexType: OptionalType | ContainerType;
OptionalType: 'optional<' inner_type=SimpleType '>';
ContainerType: kind=ContainerKind  '<' inner_type=Type '>';
ContainerKind: 'list' | 'set' | 'map';
```

My entity:
```
customer = record +c {
    id: i64;
    name: string;
    addrress: optional<string>;
    set_list : list<set<string>>;
} deriving (eq, ord, parcelable)
```

2 - I need support entity as type of entity field. Example:

```
rec: record_with_derivings;
```

The  "record_with_derivings" is another entity. So i will support simple type (SimpleType: 'i8' | 'i16' | 'i32' | 'i64' | 'f32' | 'f64' | 'string' | 'date' | 'binary' | 'bool') and any entity name that will be check after the parser.

```
record_with_derivings = record {
    eight: i8;
    sixteen: i16;
    thirtytwo: i32;
    sixtyfour: i64;
    fthirtytwo: f32;
    fsixtyfour: f64;
    d: date;
    s: string;
} deriving (eq, ord, parcelable)

record_with_nested_derivings = record {
    key: i32;
    rec: record_with_derivings;
} deriving (eq, ord, parcelable)
```

Thanks.

**Comment by goto40** [comment]
I will take a look.

Are eq, ord, and parcelable just strings in terms of the model? Or do they identify, e.g., another  'Record'?

**Comment by paulocoutinhox** [comment]
Hi,

They are strings.

Thanks.

**Comment by goto40** [comment]
The only problem I saw was the "," you expect before each deriving (see commen "CHANGED" in the grammar below)...

I also added correct references instead of a simple string for "SimpleType"...

```python
from textx import metamodel_from_str
from textx.export import model_export

grammar = r'''
  RecordModel:
     records+=Record
  ;

  Record:
     name=ID '=' 'record' flags*=Flag '{'
     fields+=RecordField
  '}'
  'deriving' '(' derivings*=Deriving ')'
  ;

  Flag: '+' name=ID; // Flag has "name"

  // CHANGED: ',' --> (','-)? 
  Deriving: (','-)? name=ID; // Deriving has "name"

  RecordField: name=ID ':' type=Type ';';  // RecordField has "name" and "type"

  RecordField: name=ID ':' type=Type ';';  // RecordField has "name" and "type"
  Type: SimpleType | ComplexType;  // Type can be simple or complex

  // WAS OK
  // SimpleType: name=ID; // Can be any string that will be check by code

  // MAYBE BETTER
  // DirectType is now either a (new) BaseType (==i8,i16,...) or a Record 
  DirectType: BaseType|Record;
  BaseType: 'basetype' name=ID ';';
  SimpleType: ref=[DirectType|ID]; // new: is a correct reference

  ComplexType: OptionalType | ContainerType;
  OptionalType: 'optional<' inner_type=SimpleType '>';
  ContainerType: kind=ContainerKind  '<' inner_type=Type '>';
  ContainerKind: 'list' | 'set' | 'map';
'''

example1 = r'''
  record_with_derivings = record {
      eight: i8;
      sixteen: i16;
      thirtytwo: i32;
      sixtyfour: i64;
      fthirtytwo: f32;
      fsixtyfour: f64;
      d: date;
      s: string;
  } deriving (eq, ord, parcelable)

  record_with_nested_derivings = record {
      key: i32;
      rec: record_with_derivings;
  } deriving (eq, ord, parcelable)
'''

class BaseType(object):
    def __init__(self, parent, name):
        self.parent = parent
        self.name = name

my_builtins = {
        'i8': BaseType(None, 'i8',),
        'i16': BaseType(None, 'i16'),
        'i32': BaseType(None, 'i32'),
        'i64': BaseType(None, 'i64'),
        'f32': BaseType(None, 'f32'),
        'f64': BaseType(None, 'f64'),
        'date': BaseType(None, 'date'),
        'string': BaseType(None, 'string')
}

mm = metamodel_from_str(grammar, classes=[BaseType], builtins=my_builtins);
m = mm.model_from_str(example1);

model_export(m, "example1.dot")
```

You can view the dot file with ```xdot```...
![example1](https://user-images.githubusercontent.com/16887130/66510063-9d07a100-ead4-11e9-93d3-9f19633e9aa7.png)

Of course you could also allow to add "BaseType"s in the model itself, if you wish.

I am not sure if I answered your question?

**Comment by goto40** [comment]
This is a even better grammaer (see http://textx.github.io/textX/stable/grammar/#repetition-modifiers):
```
...
  Record:
     name=ID '=' 'record' flags*=Flag '{'
     fields+=RecordField
  '}'
  'deriving' '(' derivings*=Deriving[','] ')'            // ADDED [',']
  ;

  Flag: '+' name=ID; // Flag has "name"
  Deriving: name=ID; // Deriving has "name"              // REMOVED ","-stuff
...
```

**Comment by goto40** [comment]
To be honest: I would also add "Deriving" as full-featured model element. I think String-based Post-processing leads to clone code in your custom code base of code already included in the (unit tested) textx code base (like I did for the BaseType stuff - see example above). No need to manage all that type stuff in you application... (what do you think? Is it clear what I mean?? Of course, your requiements may be of that kind that you need to it your own way...).

The code above has the nice ability that "record_with_derivings.thirtytwo" references (ref) the same element as "record_with_nested_derivings.key" (see PNG-image above of the dot file, in the lower-left part).

**Comment by paulocoutinhox** [comment]
Hi,

Im using this:

```
RecordModel:
   records+=Record
;

Record:
   name=ID '=' 'record' flags*=Flag '{'
   fields+=RecordField
'}'
'deriving' '(' derivings*=Deriving[','] ')'
;

Flag: '+' name=ID; // Flag has "name"
Deriving: name=ID; // Deriving has "name"
RecordField: name=ID ':' type=Type ';';  // RecordField has "name" and "type"
Type: SimpleType | ComplexType;  // Type can be simple or complex
SimpleType: name=ID; // Can be any string that will be check by code because can be filled from external sources
ComplexType: OptionalType | ContainerType;
OptionalType: 'optional<' inner_type=SimpleType '>';
ContainerType: kind=ContainerKind  '<' inner_type=Type '>';
ContainerKind: 'list' | 'set' | 'map';
```

But get this error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyginny", line 11, in <module>
    load_entry_point('pyginny', 'console_scripts', 'pyginny')()
  File "/Users/paulo/Developer/workspaces/python/pyginny/pyginny/cli.py", line 77, in main
    found_command.run()
  File "/Users/paulo/Developer/workspaces/python/pyginny/pyginny/commands/generate.py", line 41, in run
    model = meta_model.model_from_file(os.path.expanduser(self.options["<file>"]))
  File "/usr/local/lib/python3.7/site-packages/textx/metamodel.py", line 568, in model_from_file
    return self.internal_model_from_file(file_name, encoding, debug)
  File "/usr/local/lib/python3.7/site-packages/textx/metamodel.py", line 605, in internal_model_from_file
    is_main_model=is_main_model)
  File "/usr/local/lib/python3.7/site-packages/textx/model.py", line 242, in get_model_from_file
    is_main_model=is_main_model, encoding=encoding)
  File "/usr/local/lib/python3.7/site-packages/textx/model.py", line 261, in get_model_from_str
    self.parse(model_str, file_name=file_name)
  File "/usr/local/lib/python3.7/site-packages/arpeggio/__init__.py", line 1478, in parse
    self.parse_tree = self._parse()
  File "/usr/local/lib/python3.7/site-packages/textx/model.py", line 226, in _parse
    expected_rules=e.rules)
textx.exceptions.TextXSyntaxError: None:13:22: error: Expected ';' at position extras/examples/records.ginny:(13, 22) => 'ring: list*<string>; '.
make: *** [sample] Error 1
```

My file:

```
customer = record +c {
    id: i64;
    name: string;
    age: i8;
    working: bool;
    weight: f32;
    height: f64;
    photo: binary;
    birth_date: date;
    number_of_houses: i16;
    number_of_cars: i32;
    number_of_sons: i64;
    list_string: list<string>;
    list_i8: list<i8>;
    list_i16: list<i16>;
    list_i32: list<i32>;
    list_i64: list<i64>;
    list_f32: list<f32>;
    list_f64: list<f64>;
    list_binary: list<binary>;
    list_date: list<date>;
    address_list: list<customer_address>
    address_set: set<customer_address>
} deriving (eq, ord, parcelable)

customer_address = record {
    id: i64;
    address: string;
}
```

**Comment by goto40** [comment]
I tried to fix your example:
 * I added a "Comment" rule to allow to comment my model (not important)
 * I changed to order of rule ```Type``` from ```ComplexType|SimpleType``` to ```SimpleType|ComplexType```, because
   * textx parser is greedy, an Simpletype is just a name (String) -- this also matches, e.g, "list" from ```ContainerType```.
   * In order to give list, optional, etc. a higher priority, you have to change the order
   * @igordejanovic: is my explanation accurate? Do we have a link into Arpeggio docs or textX docs for this aspect?
  * I added ```added (...)?``` to your grammar to make  'deriving' optional in rule ```Record```.
  * I added some missing semicolons on the model
```
from textx import metamodel_from_str
from textx.export import model_export

grammar = r'''
RecordModel:
   records+=Record
;

Record:
   name=ID '=' 'record' flags*=Flag '{'
   fields+=RecordField
'}'
('deriving' '(' derivings*=Deriving[','] ')')? // added (...)? (optional 'deriving')
;

Flag: '+' name=ID; // Flag has "name"
Deriving: name=ID; // Deriving has "name"
RecordField: name=ID ':' type=Type ';';  // RecordField has "name" and "type"
Type: ComplexType|SimpleType;  // Type can be simple or complex -- ORDER (greedy parser)
SimpleType: name=ID; // Can be any string that will be check by code because can be filled from external sources
ComplexType: OptionalType | ContainerType; 
OptionalType: 'optional<' inner_type=SimpleType '>';
ContainerType: kind=ContainerKind  '<' inner_type=Type '>';
ContainerKind: 'list' | 'set' | 'map';
Comment: /\/\/.*/;
'''

example1 = r'''
customer = record +c {
    id: i64;
    name: string;
    age: i8;
    working: bool;
    weight: f32;
    height: f64;
    photo: binary;
    birth_date: date;
    number_of_houses: i16;
    number_of_cars: i32;
    number_of_sons: i64;
    list_string: list<string>;
    list_i8: list<i8>;
    list_i16: list<i16>;
    list_i32: list<i32>;
    list_i64: list<i64>;
    list_f32: list<f32>;
    list_f64: list<f64>;
    list_binary: list<binary>;
    list_date: list<date>;
    address_list: list<customer_address>; // semicolon missing
    address_set: set<customer_address>; // semicolon missing
} deriving (eq, ord, parcelable)

customer_address = record {
    id: i64;
    address: string;
}
'''

class BaseType(object):
    def __init__(self, parent, name):
        self.parent = parent
        self.name = name

my_builtins = {
        'i8': BaseType(None, 'i8',),
        'i16': BaseType(None, 'i16'),
        'i32': BaseType(None, 'i32'),
        'i64': BaseType(None, 'i64'),
        'f32': BaseType(None, 'f32'),
        'f64': BaseType(None, 'f64'),
        'date': BaseType(None, 'date'),
        'string': BaseType(None, 'string')
}

mm = metamodel_from_str(grammar, classes=[BaseType], builtins=my_builtins);
m = mm.model_from_str(example1);

model_export(m, "example1.dot")
```

**Comment by paulocoutinhox** [comment]
Hi,

It works.

Can i add more types inside same "grammar"?

I want add now enums, interfaces etc.

Thanks.

**Comment by goto40** [comment]
Of course you can add more things like the ```Record``` in your grammar. See also our unittests for many examples...

You can do, e.g.,
```
RecordModel:
   (
   records+=Record
   |
   enums+=Enum
   )*
;

Record:
   'record' name=ID flags*=Flag '{'
   fields+=RecordField
'}'
('deriving' '(' derivings*=Deriving[','] ')')? 
;

Enum:
   'enum' name=ID flags*=Flag '{'
   fields+=EnumField
'}'
;

Flag: '+' name=ID; // Flag has "name"
Deriving: name=ID; // Deriving has "name"
RecordField: name=ID ':' type=Type ';';  // RecordField has "name" and "type"

EnumField: name=ID '=' value=INT';';
...
```

Note: I changed ```"r1 = record {...}"``` to ```"record r1 {...}"```.
A discriminator/token at the beginning of your rule makes things easier...

And with this model something like
```
enum Customer_kind {
    new = 0;
    normal = 1;
    premium = 2;
}

record customer +c {
    id: i64;
    name: string;
    kind: Customer_kind;
    age: i8;
    address_list: list<optional<customer_address>>;
} deriving (eq, ord, parcelable)

record customer_address {
    id: i64;
    address: string;
}
```

Is this what you had in mind?

(Full example: [example2.zip](https://github.com/textX/textX/files/3720756/example2.zip), see html file included, can be recompiled with [pweave](http://mpastell.com/pweave/))

More examples, concerning inheritance (is this what you meant with interfaces?), see unittests... e.g., allowing https://github.com/textX/textX/blob/master/tests/functional/test_scoping/components_model1/example_inherit1.components (components extending other components): 
```
package interfaces {
  interface B
  interface C
}
package base {
  interface A
  interface D
  component Start {
    out output1 (format A)
  }
  component Middle extends Start, End {
    in input2 (format A,interfaces.B,interfaces.C)
    out output2 (format interfaces.B,interfaces.C,D)
  }
  component End {
    in input3 (format interfaces.B,interfaces.C,D)
  }
}

package usage {
  instance start : base.Start
  instance action1 : base.Middle
  instance action2 : base.Middle
  instance action3 : base.Middle
  instance end : base.End

  connect start.output1   to action1.input2
  connect action1.output2 to action2.input3 // inheritance
  connect action2.output1 to action3.input2 // inheritance
  connect action3.output2 to end.input3
}
```
