### ISSUE TITLE
Recursion difference with Arpeggio and textX

### ISSUE THREAD

**Issue by SnookEE** [textX/textX#24]
The following grammar definition in Arpeggio works properly and is able to parse a
python arithmetic string.

``` python
def expression(): return op_prec6
def op_prec6():   return op_prec5,  ZeroOrMore(['|'],              op_prec5)
def op_prec5():   return op_prec4,  ZeroOrMore(['^'],              op_prec4)
def op_prec4():   return op_prec3,  ZeroOrMore(['&'],              op_prec3)
def op_prec3():   return op_prec2,  ZeroOrMore(['<<','>>'],        op_prec2)
def op_prec2():   return op_prec1,  ZeroOrMore(['+','-'],          op_prec1)
def op_prec1():   return op_prec0,  ZeroOrMore(['*','/','%','//'], op_prec0)
def op_prec0():   return op_prime,  ZeroOrMore(['**'],             op_prime)
def op_unary():   return                       ['-','+','~'],      op_prime
def op_prime():   return [("(", expression, ")"),number,op_unary]
def calc():       return OneOrMore(expression), EOF
def number():     return _(r'\d+')
```

but when that same grammar is expressed in the textX syntax it fails with an infinite recursion.

``` python
arith_grammar = '''
/*  2 */ expression: op_prec6;
/*  3 */ op_prec6:   op_prec5 | ('|'                         | op_prec5)*;
/*  4 */ op_prec5:   op_prec4 | ('^'                         | op_prec4)*;
/*  5 */ op_prec4:   op_prec3 | ('&'                         | op_prec3)*;
/*  6 */ op_prec3:   op_prec2 | ('<<' | '>>'                 | op_prec2)*;
/*  7 */ op_prec2:   op_prec1 | ('+'  | '-'                  | op_prec1)*;
/*  8 */ op_prec1:   op_prec0 | ('*'  | '\/' | '%' | '\/\/'  | op_prec0)*;
/*  9 */ op_prec0:   op_prime | ('**'                        | op_prime)*;
/* 10 */ op_unary:              ('-'  | '+' | '~'            | op_prime);
/* 11 */ op_prime: ('(' expression ')') | INT | op_unary;
/* 12 */ calc: expressions+=expression;
'''

arith_meta = metamodel_from_str(arith_grammar)
metamodel_export(arith_meta, 'arith_model.dot')
```

The error message is as follows

```
Traceback (most recent call last):
  File "C:/home/workspace_cdt/fpga_projects/python/grammer/meta-hdl.py", line 134, in <module>
    arith_meta = metamodel_from_str(arith_grammar)
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\metamodel.py", line 474, in metamodel_from_str
    language_from_str(lang_desc, metamodel)
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\textx.py", line 857, in language_from_str
    lang_parser = parser.getASG()
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\arpeggio\__init__.py", line 1433, in getASG
    sem_actions[sa_name].second_pass(self, asg_node)
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\textx.py", line 354, in second_pass
    self._resolve_rule_refs(grammar_parser, model_parser)
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\textx.py", line 284, in _resolve_rule_refs
    cls._tx_peg_rule = resolve(cls._tx_peg_rule, cls.__name__)
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\textx.py", line 278, in resolve
    return _inner_resolve(node, cls_rule_name)
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\textx.py", line 247, in _inner_resolve

...Repeat enough times to blow up the stack...

  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\textx.py", line 253, in _inner_resolve
    if initial_rule_name in model_parser.metamodel:
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\metamodel.py", line 411, in __contains__
    self[name]
  File "C:\Anaconda2\envs\parse_env\lib\site-packages\textx\metamodel.py", line 377, in __getitem__
    if name in self._current_namespace:
RecursionError: maximum recursion depth exceeded
```

Thank you for your work.

**Comment by SnookEE** [comment]
I pulled down master of Arpeggio and TextX and confirmed that this issue still exists there.

**Comment by igordejanovic** [comment]
From a quick look those grammars are not the same. 
You have a left recursion in the textX version.

```
op_unary:              ('-'  | '+' | '~'            | op_prime);
op_prime: ('(' expression ')') | INT | op_unary;
```

on `op_prime` and `op_unary` alternatives.
To have the same rules as in Arpeggio version you will have to rewrite all rules to be of the form:

```
...
op_prec4:   op_prec3 | ('&' op_prec3)*;
op_prec3:   op_prec2 | ( ('<<' | '>>')  op_prec2))*;
...
op_unary:              ('-'  | '+' | '~') op_prime;
op_prime: ('(' expression ')') | INT | op_unary;
...
```

`|` is [ordered choice](http://igordejanovic.net/textX/grammar/#ordered-choice) (alternative). Writing expression just one after another is a [sequence](http://igordejanovic.net/textX/grammar/#sequence) in textX.

BTW, to have a meaningful textX grammar you should capture your matches using textX [assignments](http://igordejanovic.net/textX/grammar/#assignments) (e.g. operators and values) or you will get whole expression as a single string as everything besides `calc` is a [match rule](http://igordejanovic.net/textX/grammar/#rule-types).
I will probably made an some expression language as an example.

**Comment by SnookEE** [comment]
Thanks I'll rework my example and report back.

**Comment by SnookEE** [comment]
I've reduced this example down to the basics presented in the [Arpeggio tutorial](http://igordejanovic.net/Arpeggio/grammars/) (sans the unary portion of the grammar.

I believe the issue still persists. It maybe a problem with my neophyte eyes, but I fail to see why there is an infinite recursion.

``` python
from textx.metamodel import metamodel_from_str
from textx.export import metamodel_export

#
# def number():     return _(r'\d*\.\d*|\d+')
# def factor():     return [number, ("(", expression, ")")]
# def term():       return factor, ZeroOrMore(["*","/"], factor)
# def expression(): return term,   ZeroOrMore(["+", "-"], term)
# def calc():       return OneOrMore(expression), EOF

# () -> sequence       -> \s+ delineated
# [] -> ordered choice ->  |  delineated

arith_grammar = '''
number: /\d*/;
factor:     number | ('(' expression ')');
term:       factor ( ('*' | '\/') factor)*;
expression: term   ( ('+' | '-')    term)*;
calc:       expressions+=expression;
'''

arith_meta = metamodel_from_str(arith_grammar)
metamodel_export(arith_meta, 'arith_model.dot')
```

I believe I understand your comment at assignment to objects. I am using this arithmetic grammar as part of a larger grammar and its purpose is simply to provide the expressions value not persist as object. Maybe an operator assignment would make the "visit" class cleaner.

**Comment by igordejanovic** [comment]
textX a bit more "object oriented". Grammar in the spirit of textX should look
like this.

```
calc:       expressions+=expression;
factor:     op=INT | ('(' op=expression ')');
term:       op=factor (op=term_op op=factor)*;
term_op:    '*' | '/';
expression: op=term  (op=expr_op op=term)*;
expr_op:    '+' | '-';
```

Notice that this grammar collects important stuff in meta-class attributes
`expressions` and `op` which will be the Python list on instances of
factor/term/expression. That way you get a nice object tree after parsing your
expression.

```
metamodel = metamodel_from_file('arith.tx')
model =  metamodel.model_from_str('2+3*5/(4-1)')
```

`model` will be an instance of `calc` class thus having `expressions` attribute
which will be Python list of `expression` class instances etc.

You can than write evaluator that will walk the tree and do the evaluation.

If you use textX just to specify grammar and build parser for simple
expressions, Arpeggio has support for various syntaxes so you may instead use
Arpeggio's PEG textual syntax.

On the other hand, you can use textX to specify grammar and directly access
Arpeggio parser instance on the meta-model.

```
meta = metamodel_from_file('arith.tx')
parse_tree = meta.parser.parse(some_str)
```

In that way you don't use textX to build your model. Instead you get a raw
parse tree and process it yourself.  In this case you can simplify grammar by
not using assignments at all as they are only used by textX to deduce
meta-model which is than used to build object graph.

```
calc:       expression;
factor:     INT | ('(' expression ')');
term:       factor (term_op factor)*;
term_op:    '*' | '/';
expression: term  (expr_op term)*;
expr_op:    '+' | '-';

```

But in this case there is no real value in using textX. (Meta)-model visualization
will be meaningless also. Just use Arpeggio.

BTW, be sure to pull `master` branches of both textX and arpeggio as I have
some fixes for recursive match rules.

**Comment by SnookEE** [comment]
Thanks for your help in figuring out those issues. Here is where it ended up. This is a fun tool, thank you for your efforts.

``` python
from textx.metamodel import metamodel_from_str
from textx.export import metamodel_export
from textx.export import model_export

small_model = False

if small_model:

# def number():     return _(r'\d*\.\d*|\d+')
# def factor():     return [number, ("(", expression, ")")]
# def term():       return factor, ZeroOrMore(["*","/"], factor)
# def expression(): return term,   ZeroOrMore(["+", "-"], term)
# def calc():       return OneOrMore(expression), EOF

# () -> sequence       -> \s+ delineated
# [] -> ordered choice ->  |  delineated

    arith_grammar = '''
    expression: term    ( ('+' | '-')    term)*;
    factor:     ('(' expression ')') | INT;
    term:       factor  ( ('*' | '\/') factor)*;
    calc:       expressions+=expression;
    '''

    arith_meta = metamodel_from_str(arith_grammar)
    metamodel_export(arith_meta, 'arith_model.dot')

    input_expr = "(2*3)+4"

    arith_expr = arith_meta.model_from_str(input_expr,debug=False)
    model_export(arith_expr, 'arith_expr.dot')

else:

    arith_grammar = '''
    expr: prec6;
    prec6:   op=prec5  (op=op6   op=prec5)*;
    prec5:   op=prec4  (op=op5   op=prec4)*;
    prec4:   op=prec3  (op=op4   op=prec3)*;
    prec3:   op=prec2  (op=op3   op=prec2)*;
    prec2:   op=prec1  (op=op2   op=prec1)*;
    prec1:   op=prec0  (op=op1   op=prec0)*;
    prec0:   op=term   (op=op0   op=term)*;
    unary:              op=opU   op=term;
    term:   ('(' op=prec6 ')') | op=number | op=unary;
    op6:  '|'                       ;
    op5:  '^'                       ;
    op4:  '&'                       ;
    op3:  '<<' | '>>'               ;
    op2:  '+'  | '-'                ;
    op1:  '*'  | '\/' | '%' | '\/\/';
    op0:  '**'                      ;
    opU:  '-'  | '+' | '~'          ;
    number: /\d+/;
    '''

    input_expr = "(2**3-1)*32--3"
    arith_meta = metamodel_from_str(arith_grammar + 'calc:    expressions+=expr;')
    metamodel_export(arith_meta, 'arith_model.dot')

    arith_expr = arith_meta.model_from_str(input_expr,debug=False)
    model_export(arith_expr, 'arith_expr.dot')
```

**Comment by igordejanovic** [comment]
Glad you like it. There are a lot of examples and several tutorials you can play around. Have fun!
