### ISSUE TITLE
error for generater target textmate

### ISSUE THREAD

**Issue by mnaderhirn** [textX/textX#360]
When I try to run the following command, i get for any of the examples in the textx reqro the following error.

```
C:\local\textX-LS\examples\strictdoc>textx generate tx_strictdoc/strictdoc.tx --target=textmate --name tx-strictdoc
Generating textmate target from models:
C:\local\textX-LS\examples\strictdoc\tx_strictdoc\strictdoc.tx
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\textx.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Python38\lib\site-packages\textx\cli\generate.py", line 111, in generate
    model_params = {k: v for k, v in custom_args.items()
  File "C:\Python38\lib\site-packages\textx\cli\generate.py", line 112, in <dictcomp>
    if k in metamodel.model_param_defs}
AttributeError: 'TextXMetaMetaModel' object has no attribute 'model_param_defs'
```

dont know how to deal with this, if more information is needed just let me know.

**Comment by igordejanovic** [comment]
Thanks for reporting. At first I thought it is a problem in [textx-gen-coloring](https://github.com/danixeee/textx-gen-coloring) generator project, but after some investigation it seems to be a regression in textX. I'm working on a fix.

**Comment by igordejanovic** [comment]
Fixed on the `master` branch.
