### ISSUE TITLE
Encoding is lost when using Multi meta-model

### ISSUE THREAD

**Issue by fgro93** [textX/textX#81]
I have model (meta-model A) which imports models of another meta-model B. Model-Files of model B do not work with `utf-8` and used encoding is lost.

I assumed the encoding would be propagated.

```
Traceback (most recent call last):
  File "...\Generator.py", line 36, in getModel
    mmA.model_from_file(filePath, encoding='iso-8859-1')
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 505, in model_from_file
    return self.internal_model_from_file(file_name, encoding, debug)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 542, in internal_model_from_file
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 260, in get_model_from_file
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 285, in get_model_from_str
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 614, in parse_tree_to_objgraph
    scope_provider.load_models(model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\providers.py", line 297, in load_models
    self._load_referenced_models(model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\providers.py", line 282, in _load_referenced_models
    filename_pattern, model=model, glob_args=self.glob_args)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\__init__.py", line 159, in load_models_using_filepattern
    self.load_model(the_metamodel, filename, is_main_model))
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\scoping\__init__.py", line 213, in load_model
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 542, in internal_model_from_file
    is_main_model=is_main_model)
  File "...\Python\Python37\lib\site-packages\textx-1.7.1-py3.7.egg\textx\model.py", line 255, in get_model_from_file
    model_str = f.read()
  File "...\Python\Python37\lib\codecs.py", line 708, in read
    return self.reader.read(size)
  File "...\Python\Python37\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 4121: invalid start byte
```

**Comment by goto40** [comment]
Can you test if the master works for you now?
