### ISSUE TITLE
How to ensure imported objects are resolved?

### ISSUE THREAD

**Issue by fgro93** [textX/textX#83]
Files/Code can be found here: https://github.com/fgro93/textX-Problem

I have the following multi meta-model:
`FModel.tx`
```
import IModel

FModel:
(imports+=Import)*
(components+=Component)*;

Import:
	'import' importURI=STRING;

Connector: 'connect' prototype=[Prototype]'.'port=[Port];

Prototype:
	'contains' component=[Component] ('as' name=ID)?;

Component: 
	'component' name=ID
	('{'(
             prototypes+=Prototype |
             ports+=Port |
             connectors+=Connector
         )*'}')?;

Port:
	'requires' interface=[Interface];
```
`IModel.tx`
```
IModel: (interfaces+=Interface)*;
Interface: name = ID;
```

And three model files:
`main.fmodel`
```
import "hasPort.fmodel"

component ConnectPort {
	contains HasPort
	
	connect HasPort.Port1
}
```
`hasPort.fmodel`
```
import "ports.imodel"

component HasPort {
	requires Port0
	requires Port1
}
```
`ports.imodel`
```
Port0
Port1
```
My python code:
```
from textx.metamodel import metamodel_from_file
from textx.scoping import MetaModelProvider
from textx.scoping.providers import FQNImportURI


class PortFQN():
    def __call__(self, obj, attr, obj_ref):
        ports = obj.prototype.ports
        for port in ports:
        #Does not work because interface is not yet resolved
            if port.interface.name == obj_ref.obj_name:
                return port
        return None

class ComponentHACK():
    def __call__(self, obj, attr, obj_ref):
        return obj.parent.parent.components[0]

class PrototypeHACK():
    def __call__(self, obj, attr, obj_ref):
        parent = obj
        while hasattr(parent, 'parent'):
            parent = parent.parent
        for model in parent._tx_model_repository.local_models.filename_to_model.values():
            return model.components[0]

if __name__ == '__main__':
    f_mm = metamodel_from_file('FModel.tx')
    i_mm = metamodel_from_file('IModel.tx')
    MetaModelProvider.add_metamodel('*.fmodel', f_mm)
    MetaModelProvider.add_metamodel('*.imodel', i_mm)

    f_mm.register_scope_providers({
        "*.interface": FQNImportURI(),
        "*.component": ComponentHACK(),
        "*.prototype": PrototypeHACK(),
        "*.port": PortFQN(),
    })
    f = f_mm.model_from_file("main.fmodel")
    print(f)
```

Problem arises in the PortFQN. I thought I can simply resolve the `Port1` by using the object references I already have in my `Component ConnectPort`, but I cannot. I cannot decide which `Port` instance I have to return from `HasPort` because they are not yet resolved, therefore I cannot access their `name` attribute. Any idea on how to solve this?

**Comment by goto40** [comment]
Try

```
from textx.scoping import MetaModelProvider, Postponed

# ...

class PortFQN():
    def __call__(self, obj, attr, obj_ref):
        ports = obj.prototype.ports
        for port in ports:
            if port.interface is None:
                return Postponed()
            if port.interface.name == obj_ref.obj_name:
                return port
        return None
```

You must return a Postponed object when you need to postpone reference resolution because dependencies need to be resolved first.

Note: with the code above your example runs on my computer without aborting with an error. No additional checks were made.

**Comment by goto40** [comment]
Hi - I am not sure if I got all the details...

I just tried to check the rest of the code:
 * Having a Prototype with optional name may cause problems, when referencing this object.
 * Objects without name cannot be referenced without extra-effort. 

It may be clearer to find another solution.
If there is an unnamed prototype, then the name must be identical to the component --> in this case a custom scope provider can be a solution.

If you omit the optional name or the reference to prototype elements, you may get a much simpler model.

**Comment by goto40** [comment]
I am looking forward to discuss some alternatives to your model...

**Comment by fgro93** [comment]
Hey,
thank you very much for your answer, I didn't know about Postponed object, I should have read the documentation more carefully. Sorry about that.

For the sake of completeness, this is the error I get running my original code:
```
Traceback (most recent call last):
  File "...\textX-Problem\Main.py", line 39, in <module>
    f = f_mm.model_from_file("main.fmodel")
  File "...\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 505, in model_from_file
    return self.internal_model_from_file(file_name, encoding, debug)
  File "...\textx-1.7.1-py3.7.egg\textx\metamodel.py", line 542, in internal_model_from_file
    is_main_model=is_main_model)
  File "...\textx-1.7.1-py3.7.egg\textx\model.py", line 260, in get_model_from_file
    is_main_model=is_main_model, encoding=encoding)
  File "...\textx-1.7.1-py3.7.egg\textx\model.py", line 285, in get_model_from_str
    is_main_model=is_main_model, encoding=encoding)
  File "...\textx-1.7.1-py3.7.egg\textx\model.py", line 636, in parse_tree_to_objgraph
    m._tx_reference_resolver.resolve_one_step()
  File "...\textx-1.7.1-py3.7.egg\textx\model.py", line 747, in resolve_one_step
    obj, attr, crossref)
  File "...\textX-Problem\Main.py", line 11, in __call__
    if port.interface.name == obj_ref.obj_name:
AttributeError: 'NoneType' object has no attribute 'name'
```

I cannot change much of my model because it's actually a xtext model which I translated to textX.

Highly appreciated your help! Thank you. I will stick to custom scope provider.

**Comment by goto40** [comment]
I will have a look at it.

fgro93 <notifications@github.com> schrieb am Mi., 29. Aug. 2018, 10:34:

**Comment by fgro93** [comment]
The Postponed approach worked for me

**Comment by goto40** [comment]
Ok.
Here another suggestion: use the new referenced_metamodels feature.

See: https://github.com/igordejanovic/textX/blob/master/docs/multimetamodel.md

```
from textx.metamodel import metamodel_from_str
from textx.scoping import MetaModelProvider, Postponed
from textx.scoping.providers import FQNImportURI

fgrammar = '''
    FModel:
    (imports+=Import)*
    (components+=Component)*;
    
    Import:
        'import' importURI=STRING;
    
    Connector: 'connect' prototype=[Prototype]'.'port=[Port];
    
    Prototype:
        'contains' component=[Component] ('as' name=ID)?;
    
    Component:
        'component' name=ID
        ('{'(
                 prototypes+=Prototype |
                 ports+=Port |
                 connectors+=Connector
             )*'}')?;
    
    Port:
        'requires' interface=[Interface];

    Comment: /\/\/.*/;
'''

igrammar='''
    IModel: (interfaces+=Interface)*;
    Interface: name = ID;
'''

class PortSP():
    """ retrieves the prototype with an interface
        which has the requested name """
    def __call__(self, obj, attr, obj_ref):
        if obj.prototype is None:
            return Postponed()
        ports = obj.prototype.component.ports
        for port in ports:
            if port.interface is None:
                return Postponed()
            if port.interface.name == obj_ref.obj_name:
                return port
        return None

class PrototypeSP():
    """ retrieves the prototype with the given name or with an interface
        which has the requested name """
    def __call__(self, obj, attr, obj_ref):
        from textx import get_children_of_type
        prototypes = get_children_of_type("Prototype",obj.parent) # only prototypes of obj!?
        for p in prototypes:
            if len(p.name)>0:
                if p.name==obj_ref.obj_name:
                    return p
            elif p.component is None:
                return Postponed()
            elif p.component.name==obj_ref.obj_name:
                return p
        return None # not found, you may raise a nice error message here

if __name__ == '__main__':
    i_mm = metamodel_from_str(igrammar)
    f_mm = metamodel_from_str(fgrammar, referenced_metamodels=[i_mm])
    MetaModelProvider.add_metamodel('*.fmodel', f_mm)
    MetaModelProvider.add_metamodel('*.imodel', i_mm)

    f_mm.register_scope_providers({
        "*.*": FQNImportURI(),
        "Connector.prototype": PrototypeSP(),
        "Connector.port": PortSP(),
    })
    f = f_mm.model_from_file("main.fmodel")
    print(f)

```

new model file (as example):

```
import "hasPort.fmodel"

component ConnectPort {
	contains HasPort
	connect HasPort.Port1
}

component ConnectPort2 {
	contains HasPort as Example
	connect Example.Port1
	//connect HasPort.Port1 // produces an error (as expected)
}

```

**Comment by goto40** [comment]
Note: 
 * the referenced_metamodels-feature is only available on the master branch. But I think it is superior to your initial solution (see https://github.com/igordejanovic/textX/blob/master/docs/multimetamodel.md for a rationale) 
 * if you need the model of an object you can call textx.get_model(obj) instead of jumping from parent to parent

If you want to 'migrate' your solution to the referenced_metamodels, you just need to
 * remove the 'import' in your grammar
 * add the referenced_metamodels parameter to the metamodel_from_file command as sketched above

**Comment by fgro93** [comment]
Thanks again for your input.

The referenced_metamodels-feature does not improve anything for me because in my actual grammar, fgrammar uses some rules of igrammar. Without the import an `Unexisting rule _____ at position (?, ?).`-Error will be thrown.

**Comment by goto40** [comment]
OK.

 * w/o Import you need the referenced_metamodels thing, else you get the
error.

 * if you use some rules in both meta models, take care to allocate any
relevant scope providers or object processors to **both** meta models.

We can now close this ticket.

fgro93 <notifications@github.com> schrieb am Di., 4. Sep. 2018, 14:13:
